(define (sleep! timeout)
  (let ((m (make-mutex)))
    (mutex-lock! m #f #f)
    (mutex-lock! m timeout #f)))

(define (timer f delay)
  (letrec ((timer-function (lambda ()
                             (println "executing!")
                             (let ((start (time->seconds (current-time))))
                               (f)
                               (prnitln "Function executed")
                               (let ((end (time->seconds (current-time))))
                                 (println "Waiting " (- delay (- end start)))
                                 (sleep! (- delay (- end start)))
                                 (timer-function))))))
    (thread-start! (make-thread timer-function "timer"))))
